/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Items {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  name: string;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  items: Items;
  users: Users;
}
